### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by torjusti** [toastedcrumpets/BlackboardQuizMaker#1]
Hi, would you be willing to add a license to this repository?

**Comment by toastedcrumpets** [comment]
Sure, I'll add a promiscuous one now. Out of interest, what are you going to do with it?

**Comment by toastedcrumpets** [comment]
Closed by commit 9b7de749dd30bcebc6050f7b34feb7c92505ab76.
Feel free to still reply even though the issue is closed.
